server:
  port: 8080
spring:
  application:
    name: my-cloud-grpc-client
  cloud:
    consul:
      discovery:
        instance-id: ${spring.application.name}:${random.int[10000,99999]}
        enabled: true
        prefer-ip-address: true
        register: true
      host: localhost
      port: 8500
    zipkin:
      enabled: false
grpc:
  client:
    grpc-my-cloud-grpc-server:
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: PLAINTEXT
