spring:
  application:
    name: my-cloud-grpc-server
  cloud:
    consul:
      discovery:
        instance-id: ${spring.application.name}:${random.int[10000,99999]}
        enabled: true
        prefer-ip-address: true
        register: true
        healthCheckInterval: 15s
        health-check-url: http://${spring.cloud.client.ip-address}:${server.port}/actuator/health
      host: localhost
      port: 8500
  zipkin:
    enabled: false
server:
  port: 8090
grpc:
  server:
    port: 9090